Rename hello world .py to app.py
changed name due to this error when executing on openshift 
ERROR: don't know how to run your application.
Please set either APP_MODULE, APP_FILE or APP_SCRIPT environment variables, or create a file 'app.py' to launch your application.